set(_CATKIN_CURRENT_PACKAGE "ac_node")
set(ac_node_VERSION "0.0.0")
set(ac_node_MAINTAINER "zcnest <zcnest@todo.todo>")
set(ac_node_PACKAGE_FORMAT "2")
set(ac_node_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "common" "dynamic_reconfigure")
set(ac_node_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "common")
set(ac_node_BUILDTOOL_DEPENDS "catkin")
set(ac_node_BUILDTOOL_EXPORT_DEPENDS )
set(ac_node_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "common" "dynamic_reconfigure")
set(ac_node_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "common" "dynamic_reconfigure")
set(ac_node_TEST_DEPENDS )
set(ac_node_DOC_DEPENDS )
set(ac_node_URL_WEBSITE "")
set(ac_node_URL_BUGTRACKER "")
set(ac_node_URL_REPOSITORY "")
set(ac_node_DEPRECATED "")